name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './mira-academy/package-lock.json'

      - name: Install dependencies
        working-directory: ./mira-academy
        run: |
          npm install
          npm list next || echo "Next.js not found!"

      - name: Create build script
        working-directory: ./mira-academy
        run: |
          echo "const { execSync } = require('child_process');" > build.js
          echo "console.log('Building Next.js site for static export...');" >> build.js
          echo "try {" >> build.js
          echo "  console.log('Running Next.js build...');" >> build.js
          echo "  execSync('npx next build', { stdio: 'inherit' });" >> build.js
          echo "  console.log('Build completed successfully!');" >> build.js
          echo "} catch (error) {" >> build.js
          echo "  console.error('Build failed:', error.message);" >> build.js
          echo "  process.exit(1);" >> build.js
          echo "}" >> build.js

      - name: Build site
        working-directory: ./mira-academy
        run: node build.js

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: mira-academy
          directory: ./mira-academy/out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }} 